# Generated by Django 3.2.3 on 2021-06-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('password', models.IntegerField(max_length=20)),
                ('player_name', models.CharField(max_length=20)),
            ],
        ),
    ]
